- name: Install web packages
  apt: pkg={{ item }} state=present
  with_items:
    - php5
    - php5-mysql
    - php5-gd
    - apache2
    - ant

- name: Remove default virtual host
  file: path=/etc/apache2/sites-enabled/000-default state=absent

- name: Copy apache owncloud configuration
  template: src=apache2-owncloud.conf dest=/etc/apache2/sites-enabled/owncloud.conf
  notify: restart apache